version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - ${APP_PORT}:443
    volumes:
      - ./app:/app
      - ./.env:/app/build/.env
      - ./${CERT_FILE}:/app/build/${CERT_FILE}
      - ./${CERT_KEY}:/app/build/${CERT_KEY}
  redis:
    image: redis:latest
    restart: always
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"
