version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - ${APP_PORT}:443
    volumes:
      - ./app:/app
      - ./.env:/app/build/.env
      - ./cert.pem:/app/build/cert.pem
      - ./key.pem:/app/build/key.pem