version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - ${APP_PORT}:443
    volumes:
      - ./app:/app
      - ./.env:/app/build/.env
      - ./domain.csr:/app/build/domain.csr
      - ./domain.key:/app/build/domain.key
      - ./webhook_cert.pem:/app/build/webhook_cert.pem
      - ./webhook_pkey.key:/app/build/webhook_pkey.key